### ISSUE TITLE
Multi touch crash

### ISSUE THREAD

**Issue by jimmythesaint82** [adafruit/Adafruit_CircuitPython_FocalTouch#9]
I'm using a
Adafruit 2.8" and 3.2" Color TFT Touchscreen Breakout v2
connected to a Metro M4 Airlift light

When a 2nd finger touches the screen the code crashes

see Serial Log:

[{'id': 0, 'y': 114, 'x': 140}]
[{'id': 0, 'y': 114, 'x': 140}]
[{'id': 0, 'y': 114, 'x': 140}]
[{'id': 0, 'y': 114, 'x': 140}]
[{'id': 0, 'y': 114, 'x': 140}]
Traceback (most recent call last):
  File "code.py", line 57, in <module>
  File "adafruit_focaltouch.py", line 110, in touched
  File "adafruit_focaltouch.py", line 146, in _read
  File "adafruit_focaltouch.py", line 141, in _read
  File "adafruit_bus_device/i2c_device.py", line 112, in write
OSError: [Errno 5] Input/output error

I can catch the error and send a fake return as below ->

def _read(self, register, length):
        """Returns an array of 'length' bytes from the 'register'"""
        with self._i2c as i2c:
            try:
                i2c.write(bytes([register & 0xFF]))
                result = bytearray(length)
                i2c.readinto(result)
                if self._debug:
                    print("\t$%02X => %s" % (register, [hex(i) for i in result]))
                return result
            except:
                buffer = bytearray()
                buffer.extend(b"\x00")
                return buffer

This is of course a quick fix so I can keep working...

Does anyone have any idea why or an idea where to look?

**Comment by kattni** [comment]
@jimmythesaint82 Are you still experiencing this issue with the latest version of CircuitPython and this library?

**Comment by kmatch98** [comment]
I encountered a crash and slightly different error message, when I touch multiple spots display.  It doesn't happen consistently with multiple touches but after < 10 times, it will likely crash.  I confirmed that the fix from @jimmythesaint82 worked since it ignores this error.

My setup:
[ESP32-S2 Saola 1R Dev Kit featuring ESP32-S2 WROVER](https://www.adafruit.com/product/4693)
Adafruit [2.8" TFT LCD with Cap Touch Breakout Board w/MicroSD Socket
PRODUCT ID: 2090](https://www.adafruit.com/product/2090)
Connected via ParallelBus
SDA and SCL have 4.7kOhm pull-up resistors tied to 3.3V ([per notes in issue here](https://github.com/adafruit/circuitpython/issues/2060))
CircuitPython version: `Adafruit CircuitPython 6.1.0-rc.1-19-g414001243-dirty on 2021-01-25; Saola 1 w/Wrover with ESP32S2`

Here's my error message:
```
Traceback (most recent call last):
  File "code.py", line 341, in <module>
  File "/lib/adafruit_focaltouch.py", line 106, in touches
  File "/lib/adafruit_focaltouch.py", line 135, in _read
  File "/lib/adafruit_focaltouch.py", line 130, in _read
  File "adafruit_bus_device/i2c_device.py", line 84, in write
OSError: [Errno 19] Unsupported operation
```

Here's my setup code:
```python
display_bus = displayio.ParallelBus(
		data0=board.IO8,
		command=board.IO4,
		chip_select=board.IO5,
		write=board.IO33,
		read=board.IO2,
		reset=board.IO1,
		)


display = adafruit_ili9341.ILI9341(display_bus,
                            width=320,
                            height=240)


#print("Setting up I2C...")
i2c = busio.I2C(board.IO42, board.IO41)
ft = adafruit_focaltouch.Adafruit_FocalTouch(i2c, debug=False)
```

**Comment by ladyada** [comment]
probably you need to check the data ready pin before reading i2c, the chip is 'busy' so isnt responding to i2c.
